### PR TITLE
Add support for Couchbase relations

### PR DESCRIPTION
**Pull request by tchlyah**
Please make sure the below checklist is followed for Pull Requests.
  - [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-umk/pull_requests) are green
  - [ ] Tests are added where necessary
  - [ ] Documentation is added/updated where necessary
  - [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-core/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by MathieuAA** [comment]
@jdubois any idea why this fails? this seems related to the sonar-scanner recently added

**Comment by jdubois** [comment]
@MathieuAA I don't get why the "sonar-scanner" command is not found, I restarted the build, let's see

**Comment by jdubois** [comment]
Still failing.... that's probably because that only works on master -> you can ignore it, and I'm going to try to disable it if it's not on master

**Comment by MathieuAA** [comment]
Good point, thanks :)

**Pull request merged**
