### PR TITLE
Fix inline javadoc

### PR DESCRIPTION
**Pull request by kaidohallik**

### CODE REVIEW

**Comment by MathieuAA** [comment]
I'll test everything tonight.

**Comment by MathieuAA** [comment]
I've pushed a huge grammar clean-up to master, can you check against your PR please? If the bug still stands, I'll change the grammar myself if need be.

**Comment by kaidohallik** [comment]
Bug described in #89 in [this comment](https://github.com/jhipster/jhipster-core/issues/89#issuecomment-264337861) still exists.

**Comment by kaidohallik** [comment]
To simplify implementation you can first remove redundant rule from `fieldDeclList`:
```
  / com:comment? SPACE* f:FIELD_NAME SPACE t:type SPACE* vl:validationList {
    return [{ name: f, type: t, validations: vl, javadoc: com }];
  }
```
This is analyzed in #92

**Comment by MathieuAA** [comment]
Alright then. I'll fix these tonight.

**Comment by MathieuAA** [comment]
I think I can safely close this, right? =)

**Comment by kaidohallik** [comment]
I would like to run `npm test` but I am getting error:
```
C:\projects\jhipster-core>npm test

> jhipster-core@1.2.2 test C:\projects\jhipster-core
> ./node_modules/mocha/bin/mocha test

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.
```
Seems that in windows change in `package.json` from [this commit](https://github.com/jhipster/jhipster-core/commit/e18afaad4c30f39f1d097bafd90d0ed9b9d1b61d) breaks `npm test`.

**Comment by MathieuAA** [comment]
@kaidohallik just run `mocha`

**Comment by MathieuAA** [comment]
@kaidohallik This is, actually, my next commit...

**Comment by kaidohallik** [comment]
Currently 1 issue remained, commented in fixing commit conversation, [here](https://github.com/jhipster/jhipster-core/commit/94705f4c9481d02a0577085308d66acd571c48b3)

**Comment by MathieuAA** [comment]
Done as of 21ac3e4

**Pull request closed without merging**
