### PR TITLE
Added 'ENTITY' as reserved keyword #6110

### PR DESCRIPTION
**Pull request by FirstSamurai**
Fixes #6110

### CODE REVIEW

**Comment by deepu105** [comment]
@FirstSamurai congrats on your first contribution

**Comment by FirstSamurai** [comment]
Thanks Deepu

**Comment by pascalgrimaud** [comment]
Congrats @FirstSamurai ! :)

**Comment by FirstSamurai** [comment]
Thank you Pascal! Thank you guys for a warm welcome. Hope to contribute more stuff, if I can. :)

**Pull request merged**
