### PR TITLE
Change default database to postgresql

### PR DESCRIPTION
**Pull request by agaspardcilia**
@MathieuAA Is there anything more to do to change that? 

To be merge once https://github.com/jhipster/generator-jhipster/issues/11736 is complete.

Please make sure the below checklist is followed for Pull Requests.
  - [ ] Checks are green
  - [ ] Tests are added where necessary
  - [ ] Documentation is added/updated where necessary
  - [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-core/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by MathieuAA** [comment]
@agaspardcilia only this file has to be updated. And quite a lot of tests ;)

**Comment by mshima** [comment]
@MathieuAA I think once jhipster-core is merged into generator-jhipster, jdl should not set default values at all, should let generator-jhipster use it defaults.

**Comment by MathieuAA** [comment]
@mshima 100% agreed, the future JDL/core/whatever module will have to consume defaults from a source :) Be it the generator or jhipster base

**Comment by mshima** [comment]
@agaspardcilia just be aware this repository is about to be discontinued.
@MathieuAA are you merging the merge PR with this repository?

**Comment by MathieuAA** [comment]
I'll handle the code changes from this repo to the "super jhipster" thing (I don't have a name for it yet, working on it). As long as the CI here passes, it should be merged. **However**, as this PR is related to v7, I won't merge it.

**Comment by mshima** [comment]
@MathieuAA are you planning to create a new repository for generator-jhipster?

**Comment by MathieuAA** [comment]
@mshima no, there's a PR in the generator for this: https://github.com/jhipster/generator-jhipster/pull/11694. It's very basic, but it's intended: refactorings, design decisions, etc. should be made after this. The PR doesn't even change the generator's behavior at all.

**Comment by MathieuAA** [comment]
Here's the [mail](https://groups.google.com/forum/#!topic/jhipster-dev/BTCO2_58F6E)

**Comment by mshima** [comment]
Yep I remember that, I was confused about your "super jhipster"

**Comment by MathieuAA** [comment]
Ah! that's the name of this thing. I know, it's a poor name but this was that or calling "the merged version" :(

**Comment by agaspardcilia** [comment]
@MathieuAA Yeah, I feel like this database change will be more about testing than making actual changes. 😅 
@mshima Alright, I just hope I'll be done with this one before this repos is discontinued then.

**Comment by MathieuAA** [comment]
@agaspardcilia Hello there! I'm tidying up the merge PR (https://github.com/jhipster/generator-jhipster/pull/11694). As this PR is quite small (tests excluded), I suggest you do another one in the generator once the merge is... merged. Or I can do the update for you. Whatever suits you best.

**Comment by pascalgrimaud** [comment]
Closing this as JCore has been merged into generator-jhipster

**Pull request closed without merging**
