### PR TITLE
Don't generate changelogDate.

### PR DESCRIPTION
**Pull request by mshima**
Let generator-jhipster create changelogDate.

Comply with https://github.com/jhipster/generator-jhipster/pull/10397

Please make sure the below checklist is followed for Pull Requests.
  - [ ] Checks are green
  - [ ] Tests are added where necessary
  - [ ] Documentation is added/updated where necessary
  - [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-core/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by MathieuAA** [comment]
Why was it closed?

**Comment by mshima** [comment]
There are 2 approaches.
This one that removes changelogDate.
The other implements reproducible build.

This patch became kind of breaking (is this safe?) and big.
The other seems to be cleaner. Uploading it tomorrow.

When I upload it tomorrow I will reopen this pr so you can decide which pr is better.

**Comment by MathieuAA** [comment]
Thank you. Tomorrow I'll be quite busy and might not review your work before the night.

**Comment by mshima** [comment]
See https://github.com/jhipster/jhipster-core/pull/409.
Feel free to close this if you prefer that PR.

**Pull request closed without merging**
