### PR TITLE
remove unused rule from grammar

### PR DESCRIPTION
**Pull request by kaidohallik**
in order to make it easier to explore jhipster/jhipster-core#89

### CODE REVIEW

**Comment by MathieuAA** [comment]
I'm not quite sure about that... Let me test it first.

**Comment by kaidohallik** [comment]
I try to give a proof why the removed second rule was redundant.
First rule is:
```
JDLComment? space* com:Comment? space* JDLComment? space* f:FIELDNAME space t:type space* vl:validationList? space* com2:Comment? space* ","? space* JDLComment? space* fdl:fieldDeclList
```
Removed second rule was:
```
com:Comment? space* f:FIELDNAME space t:type space* vl:validationList
```
Let's compare rules from the beginning to the end:
- the first rule has extra `JDLComment? space*` - empty string fits that
- common part `com:Comment? space*`
- the first rule has extra `JDLComment? space*` - empty string fits that
- common part `f:FIELDNAME space t:type space*`
- the first rule has `vl:validationList?` and the second rule had `vl:validationList` - this second part of the rule matches the first part of the rule
- the first rule has extra `space* com2:Comment? space* ","? space* JDLComment? space*` - empty string fits that
- first rule has extra `fdl:fieldDeclList` - it can be empty because of the third rule of the fieldDeclList: `""`

And `npm test` was successful after removing the second rule.
And my JDL worked identically after removing the second rule.

**Comment by MathieuAA** [comment]
Did you try with only one field in the entity?

**Comment by kaidohallik** [comment]
Just tested, yes works. It's also covered by `npm test`, for example entity B from test added by you yesterday.

**Comment by MathieuAA** [comment]
Closed as it was removed in 94705f4

**Pull request closed without merging**
