### PR TITLE
Fix parsing of relationships to User in JSON parser

### LINKED ISSUE #79: Relationships to User entity are missed when exporting Json to JDL
Obviously, I forgot this use case...

### PR DESCRIPTION
**Pull request by cbornet**
Fix #79

### CODE REVIEW

**Comment by MathieuAA** [comment]
Thanks, I'll try to test it and merge it before the end of the week.

**Comment by MathieuAA** [comment]
A conflict exist, mind resolving it?

**Comment by MathieuAA** [comment]
I'll merge it right after.

**Comment by cbornet** [comment]
Done.

**Pull request merged**
