### PR TITLE
add support for java.time.Duration

### PR DESCRIPTION
**Pull request by massimosiani**
This is the core changes needed to support java.time.Duration.
Because I am not familiar with the JDL tool (my fault, it looks great!), any feedback is very very very welcome.
Thank you!

see https://github.com/jhipster/generator-jhipster/issues/9095

Please make sure the below checklist is followed for Pull Requests.
  - [x] [Travis tests](https://travis-ci.org/jhipster/jhipster-umk/pull_requests) are green
  - [x] Tests are added where necessary
  - [x] Documentation is added/updated where necessary
  - [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-core/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by MathieuAA** [comment]
@massimosiani Only one thing left to do is to update the JDL page [here](https://github.com/jhipster/jhipster.github.io/blob/master/pages/jdl.md)

**Comment by massimosiani** [comment]
Hi @MathieuAA, just to confirm, is it this [one](https://github.com/jhipster/jhipster.github.io/pull/711/files)?

**Comment by MathieuAA** [comment]
Perfect!

**Comment by murdos** [comment]
@MathieuAA : I'm ready to merge the PR on generator-jhipster. Could we merge this one?

**Comment by jdubois** [comment]
Thanks & congrats @massimosiani for your first PR to jhipster-core !

**Pull request merged**
