### PR TITLE
Validator spec

### PR DESCRIPTION
**Pull request by bd82**
This is the version after @MathieuAA made corrections on #231

### CODE REVIEW

**Comment by bd82** [comment]
I still got 4 commits here somehow, just squash them 🙈

**Comment by bd82** [comment]
oh wow still a yarn lock here, i'm going slightly mad 😄

**Comment by MathieuAA** [comment]
@bd82 it's nothing, you're work is great

**Comment by bd82** [comment]
@MathieuAA don't worry I'm saying it with a laugh, 😄 

Git managed to defeat me 😿

**Pull request closed without merging**
