### PR TITLE
Chevrotain migration.

### PR DESCRIPTION
**Pull request by bd82**
I manually re-based on top of the current upstream master
So will have merge conflicts when trying to create a pull request to the
chevrotain-migration branch.

perhaps we need a new migration branch?
Or maybe we are at a point we can consider merging this to master soon?

### CODE REVIEW

**Comment by MathieuAA** [comment]
I'm going to release a version soon. I can take care of that afterwards

**Comment by bd82** [comment]
I am rebasing this again.
Need to fix:
- [ ] 4 tests are failing
- [ ] review config properties again.
- [ ] Making array braces optional (recent change) will create ambiguities again.
       - I think even in pegjs grammar.

**Comment by bd82** [comment]
@MathieuAA 

What is this syntax:
https://github.com/jhipster/jhipster-core/blob/2a8cfa9460288f00f51239ba8577b6ad54285878/test/test_files/simple.jdl#L10

Meaning there is an opening parenthesis without a matching closing parenthesis.
Is it valid?

**Comment by MathieuAA** [comment]
Well spotted, gotta fix that. I'll begin the work on the migration tomorrow by the wayLe 22 juin 2018 20:25, Shahar Soel <notifications@github.com> a écrit :@MathieuAA
What is this syntax:
https://github.com/jhipster/jhipster-core/blob/2a8cfa9460288f00f51239ba8577b6ad54285878/test/test_files/simple.jdl#L10
Meaning there is an opening parenthesis without a matching closing parenthesis.
Is it valid?

**Comment by bd82** [comment]
> I'll begin the work on the migration tomorrow

Cool. I will provide additional pull requests as I review the configuration properties syntax.

**Comment by colameo** [comment]
Please let me know if you change the syntax of the config stuff. I've already implemented everything in the JH IDE. Had to work a bit around to have a good content assist "behavior" (the grammar / parse rules inside config { ... } makes the content assist logic a bit ambiguous / hard to handle). However, now it works and hope it stays stable for a while ;-)

**Comment by bd82** [comment]
> Please let me know if you change the syntax of the config stuff.

I am not changing any config syntax, just making sure nothing has changed as rebase can cause
changes to get lost... (duplicate maintenance...)

**Pull request merged**
