### PR TITLE
Fix javadoc detection

### LINKED ISSUE #291: Commented section falsely interpred as javadoc
##### **Overview of the issue**

Commented code is interpreted as javadoc

##### **Motivation for or Use Case**

Incorrect and unexpected behavior.

##### **Reproduce the error**

Import following JDL:
```
/*
entity AnotherDisabledEntity {}
*/
entity Group {
	name String required minlength(3),
	handle String required minlength(2)
}
```
is interpreted as if `entity AnotherDisableEntity {}` was the javadoc of the `Group` entity

The following test should be changed, the comment should be `undefined`:
https://github.com/jhipster/jhipster-core/blob/master/test/spec/parser/document_parser_test.js#L545

##### **Suggest a Fix**

Create a new JAVADOC token with the correct pattern (`/** */`): 
https://github.com/jhipster/jhipster-core/blob/master/lib/dsl/lexer.js#L99

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by murdos**
Fixes #291

Please make sure the below checklist is followed for Pull Requests.
  - [x] [Travis tests](https://travis-ci.org/jhipster/jhipster-umk/pull_requests) are green
  - [x] Tests are added where necessary
  - [x] Documentation is added/updated where necessary
  - [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-core/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by murdos** [comment]
This is a naive fix, feel free to correct me if I'm wrong.
I've renamed the lexer token, and I think more renaming should be done (e.g. JDLEntity.comment -> JDLEntity.javadoc), but I guess it will break external API.

**Comment by MathieuAA** [comment]
Thanks I'll review this first thing tomorrow!

**Comment by MathieuAA** [comment]
I don't understand why you've renamed the token. What was the issue with `COMMENT`?

**Comment by MathieuAA** [comment]
@murdos This PR is good to be merged, thanks! I'll let you merge it whenever you want. Can you please do a `npm run bundle` before and commit the change? It updates the parsing system with the latest changes.
Thanks :)

**Comment by murdos** [comment]
@MathieuAA I've also run `npm run prepare` so diagrams have been updated too

**Pull request merged**
