### PR TITLE
Add Sonar analysis

### PR DESCRIPTION
**Pull request by Shaolans**
Please make sure the below checklist is followed for Pull Requests.
  - [x] Checks are green
  - [ ] Tests are added where necessary
  - [ ] Documentation is added/updated where necessary
  - [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-core/blob/master/CONTRIBUTING.md) are followed

It would be great to have a code quality check on the master at all time.
Since the coverage and report is already done, we just need to analyze and push to sonarcloud.
We also need to supply a SONAR_TOKEN secret as well

### CODE REVIEW

**Comment by MathieuAA** [comment]
@Shaolans nice, thanks! I'll let you merge it when you want to.

**Comment by Shaolans** [comment]
We just need someone to supply the SONAR_TOKEN and it should be good to go.
ping @pascalgrimaud

**Comment by DanielFran** [comment]
@Shaolans it is just missing the badge in readme...

**Comment by MathieuAA** [comment]
I've added the badge

**Pull request merged**
