### PR TITLE
Add neo4j support

### PR DESCRIPTION
**Pull request by atomfrede**
This prepares for the upcoming neo4j  support. I hope all changes are correct. But importing a jdl into an application with neo4j support worked very well.

Please make sure the below checklist is followed for Pull Requests.
  - [ ] Checks are green
  - [ ] Tests are added where necessary
  - [ ] Documentation is added/updated where necessary
  - [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-core/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by atomfrede** [comment]
Need to rebase as it seems.

**Comment by atomfrede** [comment]
@MathieuAA When the part in the main generator is merged, can jhipster-core be released or is there a problem with the breaking change for JDL application class?

**Comment by MathieuAA** [comment]
There is a small breaking change in the API, but the generator isn't impacted.
Just tell me when you plan to merge the PR so that I can release

**Comment by MathieuAA** [comment]
@atomfrede I'd love to have that for the next release, do you know when this can one be merged?

**Comment by atomfrede** [comment]
I need to fix the pr in the main generator first I would say. Otherwise the options won't work yet.

**Comment by MathieuAA** [comment]
Okay then! I'm ready to make a release, just tell me when you're comfortable merging this and I'll follow.

**Pull request merged**
