### PR TITLE
Added NodeJS workflow

### PR DESCRIPTION
**Pull request by MathieuAA**
For GH actions, only on PRs to master for now

Please make sure the below checklist is followed for Pull Requests.
  - [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-core/pull_requests) are green
  - [ ] Tests are added where necessary
  - [ ] Documentation is added/updated where necessary
  - [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-core/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@MathieuAA : nice job here. I'd like you have your opinion about GH actions. Do you plan to remove Travis ? Stay with GH actions only ? What about Azure Pipelines ?

**Comment by MathieuAA** [comment]
@pascalgrimaud Hi! My short-term goal was to try it (check!), and remove the Travis checks but keep Azure pipelines for the time being.
What do you think?

**Comment by pascalgrimaud** [comment]
I'd like you remove Travis for all our organization.

Then, use GH actions for repo where the CI is simple (npm install, build, test).
Azure should be use only when there is some generation + configs, so when the CI is complex

Thanks for adding this, it will help me to start understanding GH actions :)

**Comment by MathieuAA** [comment]
I'll try. Gotta do a major release today for JCore and update the docs before I'll be able to play with actions a bit more.

**Comment by MathieuAA** [comment]
So I can remove the Azure check here too then?

**Comment by pascalgrimaud** [comment]
Let's wait a little bit to see how GH actions works. If it works well, then yes, let's remove Travis and Azure. 

For Azure, I'll do it, because I need to delete jhipster-core in Azure orga first.

**Comment by MathieuAA** [comment]
Roger that

**Pull request merged**
