### PR TITLE
Implemented the single & multi app export

### PR DESCRIPTION
**Pull request by MathieuAA**
Please make sure the below checklist is followed for Pull Requests.
  - [x] [Travis tests](https://travis-ci.org/jhipster/jhipster-core/pull_requests) are green
  - [X] Tests are added where necessary
  - [X] Documentation is added/updated where necessary
  - [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-core/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by MathieuAA** [comment]
@Shaolans this is my version of the single & multi app + entities export, can you have a look and compare with yours? if you have the time of course

**Comment by Shaolans** [comment]
The logic behind seems to be similar to me 👍. The major difference is about exporting multi apps, I am exporting on just one jdl as you are exporting a jdl on each apps. I don't know which is the better one, I was thinking that if we have subfoldes containing apps, it sould probably correponds to microservices apps used for an entire project, thus keeping all into one jdl but I might be wrong.

**Comment by MathieuAA** [comment]
Nop, that's a good point! Your logic is better here.

**Comment by MathieuAA** [comment]
@Shaolans it's way better, thanks for the review.

**Pull request merged**
