### PR TITLE
Forward skipEntityFilesGeneration to entity exporter.

### PR DESCRIPTION
**Pull request by mshima**
Please make sure the below checklist is followed for Pull Requests.
  - [ ] Checks are green
  - [ ] Tests are added where necessary
  - [ ] Documentation is added/updated where necessary
  - [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-core/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mshima** [comment]
@MathieuAA let me know if I should keep working on this.

**Comment by mshima** [comment]
Kind of, those options at import isn’t that useful.
But since the options exists...

**Comment by mshima** [comment]
The minor bug is that .jhipster is created when it shouldn't.

**Comment by MathieuAA** [comment]
Yeah I got that. It can be misleading too. Thanks :)

**Pull request merged**
